### PR TITLE
Clarified the default VPC issue further

### PR DESCRIPTION
**Pull request by volkertb**

### CODE REVIEW

**Comment by volkertb** [comment]
@HerrmannHinz Hmmm... You might want to squash this PR. Let me know if you need any help merging this. Thanks.

**Comment by HerrmannHinz** [comment]
@volkertb sure. help would be appreciated.

**Comment by volkertb** [comment]
@HerrmannHinz  Alright then. Feel free to merge this PR or provide feedback if you would like to see some changes first. 🙂 Or did I create this PR incorrectly?

**Comment by HerrmannHinz** [comment]
@volkertb merged :)

**Pull request merged**
